Fix `django.utils.inspect` stubtest errors on Python 3.14+
The following errors are only present when running stubtest on Python
3.14+ due to some things added conditionally:

```
error: django.utils.inspect.lock is not present in stub
Stub: in file /home/nick/Sources/_external/django-stubs/django-stubs/utils/inspect.pyi
MISSING
Runtime:
<unlocked _thread.lock object at 0x7f44a774d490>

error: django.utils.inspect.safe_signature_from_callable is not present in stub
Stub: in file /home/nick/Sources/_external/django-stubs/django-stubs/utils/inspect.pyi
MISSING
Runtime:
def (obj, *, follow_wrapper_chains=True, skip_bound_arg=True, globals=None, locals=None, eval_str...
```