Fix missing at runtime errors (second batch) (#2636)
* `LogoutView.get_next_page` renamed to `get_success_url` in 4.1

* Removed in 5.2  (`create_spatial_indexes`)

* Remove `admin_list.DOT` symbol

* Remove `INTERNAL_RESET_URL_TOKEN`

* Remove `PostGISAdapter.prepare`

Removed in 4.2 https://github.com/django/django/blob/stable/4.2.x/django/contrib/gis/db/backends/postgis/adapter.py

* QuerySet does not implement `__reversed__`

AttributeError: 'QuerySet' object has no attribute '__reversed__'

* Fix `psycopg2_version` types

* InvalidQuery removed in 4.0

* The ``django.db.models.query_utils.InvalidQuery`` exception class is removed.

* `save_m2m` is dynamically added on modelforms

* Remove ifequal nodes

* MultiColSource removed in django 5.2