BaseForm.add_error: Use covariant types
Without this change, the user has to pass in exactly these types, since `list` and `dict` are invariant in the value type.